"""your message

Revision ID: e5eb360876a6
Revises: 4a719583559f
Create Date: 2024-07-03 14:57:01.362025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5eb360876a6'
down_revision = '4a719583559f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
